version: 2
updates:
- package-ecosystem: nuget
  directories:
    - "src/Pure.Linq.Conditions"
    - "src/Tests/Pure.Linq.Conditions.Tests"
  schedule:
    interval: daily
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
